# Dotnet-XYZ © 2021

name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: build.sh
      run: >-
        NUGET_API_KEY=${{ github.token }}
        NUGET_SOURCE=https://nuget.pkg.github.com/dotnet-xyz/index.json
        POSTGRES_PASSWORD=P@ssw0rd
        SERVICE_REPOSITORY_URL=https://github.com/${{ github.repository }}
        SERVICE_VERSION=1.0.${{ github.run_number }}
        sh build.sh
    - name: docker login
      run: docker login --username=${{ github.actor }} --password=${{ github.token }} ghcr.io
    - name: docker tag
      run: docker tag ${{ github.repository }}:1.0.${{ github.run_number }} ghcr.io/${{ github.repository }}:1.0.${{ github.run_number }}
    - name: docker push
      run: docker push ghcr.io/${{ github.repository }}:1.0.${{ github.run_number }}
